// Florida metro / population-center regions used to rotate the daily
// sourcing search so coverage spreads across the whole state over time
// instead of hammering the same few cities every run.
export const FLORIDA_REGIONS: string[] = [
  "Miami",
  "Miami Beach",
  "Hialeah",
  "Kendall",
  "Homestead",
  "Doral",
  "Fort Lauderdale",
  "Hollywood",
  "Pembroke Pines",
  "Coral Springs",
  "Plantation",
  "Boca Raton",
  "Delray Beach",
  "West Palm Beach",
  "Boynton Beach",
  "Port St. Lucie",
  "Fort Pierce",
  "Vero Beach",
  "Stuart",
  "Melbourne",
  "Palm Bay",
  "Titusville",
  "Orlando",
  "Kissimmee",
  "Winter Park",
  "Sanford",
  "Ocoee",
  "Deltona",
  "Daytona Beach",
  "Ormond Beach",
  "New Smyrna Beach",
  "Gainesville",
  "Ocala",
  "The Villages",
  "Tampa",
  "St. Petersburg",
  "Clearwater",
  "Brandon",
  "Wesley Chapel",
  "Spring Hill",
  "Lakeland",
  "Winter Haven",
  "Bradenton",
  "Sarasota",
  "Port Charlotte",
  "Punta Gorda",
  "Fort Myers",
  "Cape Coral",
  "Naples",
  "Bonita Springs",
  "Key West",
  "Marathon",
  "Tallahassee",
  "Panama City",
  "Destin",
  "Fort Walton Beach",
  "Pensacola",
  "Jacksonville",
  "Jacksonville Beach",
  "St. Augustine",
  "Palm Coast",
];
